[build]
  command = "cd client && pnpm install && pnpm build"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  environment = { NODE_ENV = "production" }
